version: 'v2.23.0'
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./data:/data/
    cap_add:
      - SYS_RESOURCE
    environment:
      - NEO4J_AUTH=none